# Generated by Django 3.0.4 on 2020-03-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200315_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
