# Generated by Django 3.0.4 on 2020-03-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('blood', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('height', models.CharField(max_length=10)),
                ('favfood', models.CharField(max_length=100)),
                ('foodtype', models.CharField(max_length=15)),
                ('diet', models.TextField(max_length=1500)),
                ('nutrient', models.TextField(max_length=1500)),
                ('disease', models.TextField(max_length=1500)),
                ('cuisines', models.TextField(max_length=1500)),
                ('medicalhistory', models.TextField(max_length=1500)),
                ('image', models.ImageField(default='', upload_to='website/images')),
            ],
        ),
    ]
