# Generated by Django 3.0.4 on 2020-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
