# Generated by Django 3.0.4 on 2020-04-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200325_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='C:\\Users\\MMG\\Desktop\\NBMRS\\minor\\media\\website\\images\\avtar.png', upload_to='website/images'),
        ),
    ]
