# Generated by Django 3.0.4 on 2020-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200406_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_time',
            field=models.BooleanField(default='False'),
        ),
    ]
